paths:
  uploads: public/uploads
  static: public
collections_config:
  posts:
    path: src/content/blog
    name: Blog Posts
    icon: article
    url: /blog/[slug]/
    disable_url: false
    _enabled_editors:
      - visual
      - content
    _inputs:
      title:
        type: text
        options:
          empty_type: string
          required: true
        cascade: true
      image_alt:
        type: text
        options:
          empty_type: string
        cascade: true
      author:
        type: text
        options:
          empty_type: string
        cascade: true
      thumb_image.image:
        type: image
        options:
          resize_style: crop
          width: 500
          height: 413
          required: true
        cascade: true
      featured_image.image:
        type: image
        options:
          resize_style: crop
          width: 1296
          required: true
        comment: The hero image used at the top of the page
        cascade: true
    add_options:
      - name: Add New Post
        icon: post_add
        schema: default
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Post
        icon: notes
  pages:
    path: src/content/pages
    icon: wysiwyg
    url: /[slug]/
    disable_url: false
    _enabled_editors:
      - visual
    _inputs:
      content_blocks:
        type: array
        options:
          empty_type: array
          disable_add: false
          disable_remove: false
          disable_reorder: false
        cascade: true
    add_options:
      - name: Add New Page
        icon: note_add
        schema: default
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Page
        icon: notes
        new_preview_url: /
      paginated_collection:
        path: .cloudcannon/schemas/paginated-collection.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  data:
    path: data
    icon: data_usage
    disable_url: true
    _inputs:
      social:
        type: array
        options:
          structures: _structures.social_links
        cascade: true
      sections:
        type: array
        options:
          structures: _structures.sections
        cascade: true
      favicon_icon:
        type: image
        comment: For the shortcut icon meta tag
        cascade: true
      favicon_image:
        type: image
        comment: For the icon meta tag
        cascade: true
      twitter_site:
        type: twitter
        label: Twitter Username
        cascade: true
      logo_url:
        comment: Link for the logo in the top left of the footer
        cascade: true
      copyright:
        comment: Automatically prefixed with the current year
        cascade: true
      enable_nav_btn:
        type: switch
        cascade: true
      nav_btn:
        options:
          preview:
            icon: smart_button
        hidden: '!enable_nav_btn'
        cascade: true
      $.primary_color:
        type: color
        options:
          format: hex
          alpha:
          empty_type:
          required: true
          required_message:
          min_length:
          min_length_message:
          max_length:
          max_length_message:
          pattern:
          pattern_message:
        cascade: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: false
collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Blogging
    collections:
      - posts
  - heading: Site Settings
    collections:
      - data
_inputs:
  image:
    type: image
    options:
      max_file_size: 5000
      max_file_size_message: >-
        For page performance, keep images under 5MB. Before uploading, consider
        processing your image to be a smaller size, or lower quality. If needed,
        this maximum can be configured in your cloudcannon.config.yml file.
    cascade: true
  button:
    type: object
    options:
      preview:
        icon: smart_button
    cascade: true
  layout:
    hidden: true
    cascade: true
  date:
    instance_value: NOW
    cascade: true
  title_suffix:
    comment: Added at the end of the title and highlighted in a different color
    cascade: true
  page_size:
    type: number
    comment: The number of collection items to list per page
    cascade: true
  content:
    type: markdown
    cascade: true
  icon:
    type: select
    options:
      allow_empty: true
      values:
        - ph-user-square
    cascade: true
  description:
    type: markdown
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      bold: true
      image_size_attributes: true
      italic: true
      link: true
      removeformat: true
    cascade: true
  seo:
    type: object
    options:
      preview:
        text:
          - Search engine optimization
        subtext:
          - key: page_description
          - Update SEO values for the page
        icon: query_stats
    comment: >-
      Set SEO values for the page. [Site
      defaults](cloudcannon:collections/data/site.json) will be used if values
      are not set on the page
    cascade: true
  page_description:
    type: text
    comment: If empty, defaults to the description set in the Site SEO data file
    cascade: true
  canonical_url:
    type: text
    comment: If empty, defaults to the URL of the page
    cascade: true
  featured_image:
    comment: If empty, defaults to the image set in the Site SEO data file
    cascade: true
  author_twitter_handle:
    type: twitter
    comment: Defaults to the twitter site value set in the Site SEO data file
    cascade: true
  no_index:
    type: checkbox
    comment: >-
      When selected this removes the page from your sitemap and adds the noindex
      robots meta tag
    cascade: true
  open_graph_type:
    type: select
    options:
      allow_empty: true
      values:
        - website
        - article
        - profile
    cascade: true
  nav_items:
    type: array
    options:
      structures: _structures.nav_items
    cascade: true
  logo:
    type: image
    cascade: true
  tags:
    type: multiselect
    options:
      allow_empty: true
      values: data.blog-tags
      empty_type: array
    cascade: true
_structures:
  features:
    style: select
    values:
      - value:
          item:
          active_feature:
        _inputs:
          active_feature:
            type: switch
            cascade: true
  sections:
    style: select
    values:
      - value:
          title:
          links:
        preview:
          icon: sort
        _inputs:
          links:
            type: array
            options:
              structures: _structures.links
              required: true
            cascade: true
  links:
    style: select
    values:
      - preview:
          icon: link
        value:
          text:
          link:
  nav_items:
    style: select
    values:
      - value:
          link:
          text:
          enable_dropdown:
          dropdown:
        _inputs:
          enable_dropdown:
            type: switch
            cascade: true
          dropdown:
            type: array
            options:
              structures: _structures.dropdown
              disable_add: false
              disable_remove: false
              disable_reorder: false
            label: Dropdown Items
            hidden: '!enable_dropdown'
            cascade: true
        preview:
          text:
            - key: text
          subtext:
            - key: link
          icon: link
  dropdown:
    style: select
    values:
      - value:
          dropdown_text:
          dropdown_link:
        _inputs:
          dropdown_link:
            type: url
            label: Link
            cascade: true
          dropdown_text:
            type: text
            label: Name
            cascade: true
        preview:
          icon: link
commit_templates:
  - label: Default message
    template_string: '[default_commit_message]'
  - label: Custom message
    template_string: '{message}'
data_config:
  blog-tags:
    path: data/blog-tags.json
  footer:
    path: data/footer.json
  navigation:
    path: data/navigation.json
  theme:
    path: data/theme.json
timezone: Etc/UTC
_structures_from_glob:
  - /.cloudcannon/*.cloudcannon.structures.yml
